name: YouTube Playlist Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytube requests
      
      - name: Scrape YouTube playlists
        run: |
          python -c "
import json
import os
from pytube import Playlist
import time
import re

# List of playlist URLs to scrape
playlists = [
    'https://www.youtube.com/playlist?list=PLx8eSI7UgsiGA9f1ztAHoemtDlfJUd5a3',
    # Add more playlists as needed
]

# Create output directory if it doesn't exist
output_dir = 'playlists'
os.makedirs(output_dir, exist_ok=True)

changes = False

for playlist_url in playlists:
    try:
        # Extract playlist ID from URL
        playlist_id_match = re.search(r'list=([\\w-]+)', playlist_url)
        if not playlist_id_match:
            print(f'Could not extract playlist ID from {playlist_url}')
            continue
            
        playlist_id = playlist_id_match.group(1)
        output_file = f'{output_dir}/{playlist_id}.json'
        
        playlist = Playlist(playlist_url)
        playlist_title = playlist.title
        print(f'Scraping playlist: {playlist_title} (ID: {playlist_id})')
        
        videos = []
        for video in playlist.videos:
            # Add a small delay to avoid rate limiting
            time.sleep(0.5)
            video_data = {
                'title': video.title,
                'url': f'https://www.youtube.com/watch?v={video.video_id}',
                'thumbnail': f'https://i.ytimg.com/vi/{video.video_id}/maxresdefault.jpg'
            }
            videos.append(video_data)
            print(f'Added video: {video.title}')
        
        playlist_data = {
            'playlist_title': playlist_title,
            'playlist_id': playlist_id,
            'playlist_url': playlist_url,
            'video_count': len(videos),
            'last_updated': time.strftime('%Y-%m-%d %H:%M:%S UTC'),
            'videos': videos
        }
            
        # Save to JSON file
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(playlist_data, f, ensure_ascii=False, indent=2)
            
        print(f'Completed playlist: {playlist_title} with {len(videos)} videos')
        changes = True
        
    except Exception as e:
        print(f'Error scraping playlist {playlist_url}: {str(e)}')

# Create an index file with all playlist IDs and titles
try:
    playlist_index = []
    for filename in os.listdir(output_dir):
        if filename.endswith('.json'):
            with open(os.path.join(output_dir, filename), 'r', encoding='utf-8') as f:
                data = json.load(f)
                playlist_index.append({
                    'playlist_id': data.get('playlist_id', ''),
                    'playlist_title': data.get('playlist_title', ''),
                    'video_count': data.get('video_count', 0),
                    'filename': filename
                })
    
    # Save index file
    with open(f'{output_dir}/index.json', 'w', encoding='utf-8') as f:
        json.dump(playlist_index, f, ensure_ascii=False, indent=2)
    
    print(f'Created index file with {len(playlist_index)} playlists')
except Exception as e:
    print(f'Error creating index file: {str(e)}')

print(f'Successfully completed scraping process')
          "
      
      - name: Check for changes
        id: git-check
        run: |
          git status
          git diff --exit-code --quiet playlists/ || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if there are changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlists/
          git commit -m "Update YouTube playlist data"
          git push